### ISSUE TITLE
No me gusta tu codigo bro

### ISSUE THREAD

**Issue by Fuentes2395** [william-monroy/Workshop-Tec#1]
Buena clase :)

**Comment by sharifnasser** [comment]
Hola

**Comment by Fuentes2395** [comment]
Buenas

**Comment by sharifnasser** [comment]
¿Listos para usar Git/GitHub con sus equipos de clase?

**Comment by william-monroy** [comment]
Hoy se soluciono los errores en el archivo index.js @Fuentes2395 @sharifnasser
